### ISSUE TITLE
[BE-195] bug: 캡차 id 값이 일정하게 hash되는 문제

### ISSUE THREAD

**Issue by kssumin** [JNU-Parking-Ticket-Project/Parking-Ticket-BE#401]
## 문제점
* 캡챠를 보여줄 때 captureId를 암호화한 code값을 사용자에게 보내준다.
* 캡챠 성공 여부를 판단할 때 해당 code값을 다시 복호화하여 captureId를 알아내고 captureId를 통해서 capture의 정답값과 사용자의 입력값을 비교하고 있다.
* 문제가 되는 이유: 특정 사용자가 code, capture 정답값을 알아내어 신청 API로 계속해서 요청을 보냄

## 원인
지금 암호화에서 사용하고 있는 SHA-256 방식의 경우 단방향 암호화이다.
* 가장 큰 문제점은 레인보우 테이블이 존재한다는 점이다.
* 레인보우 테이블: 해시 함수를 사용하여 변환 가능한 모든 해시 값을 저장시켜 놓은 표이다. (레인보우 테이블로부터 captureCode의 captureId 값을 알아낼 수 있다.)
* 즉 입력값이 같다면(captureId) 해싱된 해시값(captureCode)는 항상 동일하다는 것이다.

## 해결방안
1. 기존 암호화(SHA-256 방식) + salt를 함께 사용하자!
* 평문에 랜덤값(salt)을 생성하여 평문+랜덤값으로 해시값을 얻는다. (기존에는 평문을 SHA-256 방식을 사용하여 바로 암호화하였다.)
* 이때 사용한 솔트(랜덤값)을 DB에 저장해둔다.
* 검증 시 저장된 솔트를 사용하여 해시값을 비교한다.

## 스키마 구조
스키마 추가가 필요해보입니다.
`다음과 같이 생각하고 있는데 더 좋은 의견 있으시면 이슈 댓글로 남겨주세요!`

```sql
-- 캡챠 사용 로그 테이블
CREATE TABLE captcha_usage_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    captcha_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    salt VARCHAR(255) NOT NULL,
    is_success BOOLEAN NOT NULL
);
```

이 스키마에서:
- `id`: 각 캡차 레코드의 고유 식별자
- `capture_id`: 원본 캡차 ID
- `user_id`: 유저 ID
- `salt`: 해시에 사용된 랜덤 salt 값
- `is_sucess`: 해당 캡챠 코드 사용 여부 
   - 같은 캡챠 코드를 통해 중복으로 캡챠 요청을 보내는 것을 막을 수 있을 것이라고 기대...

## 구현 단계
1. 스키마 업데이트: 위 스키마대로 DB 테이블 생성
2. 캡차 생성 시 로직 수정:
   - Salt 생성
   - Salt를 사용해 captureId 해시
   - Salt를 DB에 저장
5. 캡차 검증 로직 수정:
   - DB에서 salt 조회
   - 입력받은 captureId와 저장된 salt로 새로 해시
   - 새로 생성한 해시와 저장된 해시 비교

## 기대 효과
- 동일한 captureId에 대해 매번 다른 captureCode 생성
- 레인보우 테이블 공격 방지

**Comment by kssumin** [comment]
해당 방식으로 진행할 예정입니다!
DB 테이블의 변경이 있을 것 같은데 괜찮을지 의견 여쭙니다! @Kwon770

**Comment by Kwon770** [comment]
제가 생각하고 전달했던 내용대로 인 것 같습니다~ salt는 난수를 생성해서 사용할 예정인가요?

**Comment by Kwon770** [comment]
DB는 제가 설계한 부분이 아니다보니 확언은 못하겠지만, 간섭이 있을 것 같지는 않네요. @BlackBean99 @LJH098 @pyg410 저희 ERD 따로 만들어 둔 것이 있을까요?

**Comment by LJH098** [comment]
ERD는 초창기에 만들어둔게 있는데 업데이트가 많이 안되어있어서 Datagrip에서 지원하는 show diagram을 통해서 확인하는게 좋을 것 같아요

**Comment by kssumin** [comment]
> 제가 생각하고 전달했던 내용대로 인 것 같습니다~ salt는 난수�를 생성해서 사용할 예정인가요?

넵!! 난수로 할 생각입니다!

**Comment by kssumin** [comment]
> 저도 크게 문제가 될 것 같진 않아요 @kssumin `스키마 업데이트: 위 스키마대로 DB 테이블 수정` 라고 하셨는데 이거는 테이블 수정이 아니라 테이블 추가를 말씀하시는거죠?

테이블 추가가 맞습니다! 수정하겠습니다 😄

**Comment by Kwon770** [comment]
금주 회의에서 테이블 구조에 대해 논의하는 김에 ERD 업데이트도 추진하면 좋겠네요~
